import { Registry } from '../types/registry';
import { AscentType } from '../types/ascent-type';

export enum PublishOptionsEnum {
  public = 'public',
  club = 'club',
  log = 'log',
  private = 'private',
}

export const ASCENT_TYPES: AscentType[] = [
  {
    value: 'onsight',
    label: 'Na pogled',
    icon: 'visibility',
    topRope: false,
    tick: true,
    topRopeTick: false,
    color: '#609CDE',
    order: 3,
  },
  {
    value: 'flash',
    label: 'Flash',
    icon: 'flash_on',
    topRope: false,
    tick: true,
    topRopeTick: false,
    color: '#999999',
    order: 2,
  },
  {
    value: 'redpoint',
    label: 'Z rdečo piko',
    icon: 'adjust',
    topRope: false,
    tick: true,
    topRopeTick: false,
    color: '#D13C2A',
    order: 1,
  },
  {
    value: 'repeat',
    label: 'Ponovitev',
    icon: 'hdr_weak',
    topRope: false,
    tick: true,
    topRopeTick: false,
    color: '#ECAAA1',
    order: 4,
  },
  {
    value: 'allfree',
    label: 'Vse prosto',
    icon: 'checkroom',
    topRope: false,
    tick: false,
    topRopeTick: false,
    color: '#1C508C',
    order: 6,
  },
  {
    value: 'aid',
    label: 'Tehnično plezanje',
    icon: 'tools_ladder',
    topRope: false,
    tick: false,
    topRopeTick: false,
    color: '#FAE9E7',
    order: 7,
  },
  {
    value: 'attempt',
    label: 'Neuspel poskus',
    icon: 'close',
    topRope: false,
    tick: false,
    topRopeTick: false,
    color: '#383838',
    order: 5,
  },
  {
    value: 't_onsight',
    label: 'Na pogled',
    icon: 'visibility',
    topRope: true,
    tick: false,
    topRopeTick: true,
    color: '#609CDE',
    order: 10,
  },
  {
    value: 't_flash',
    label: 'Flash',
    icon: 'flash_on',
    topRope: true,
    tick: false,
    topRopeTick: true,
    color: '#999999',
    order: 9,
  },
  {
    value: 't_redpoint',
    label: 'Z rdečo piko',
    icon: 'adjust',
    topRope: true,
    tick: false,
    topRopeTick: true,
    color: '#D13C2A',
    order: 8,
  },
  {
    value: 't_repeat',
    label: 'Ponovitev',
    icon: 'hdr_weak',
    topRope: true,
    tick: false,
    topRopeTick: false,
    color: '#ECAAA1',
    order: 11,
  },
  {
    value: 't_allfree',
    label: 'Vse prosto',
    icon: 'checkroom',
    topRope: true,
    tick: false,
    topRopeTick: false,
    color: '#1C508C',
    order: 13,
  },
  {
    value: 't_aid',
    label: 'Tehnično plezanje',
    icon: 'tools_ladder',
    topRope: true,
    tick: false,
    topRopeTick: false,
    color: '#FAE9E7',
    order: 14,
  },
  {
    value: 't_attempt',
    label: 'Neuspel poskus',
    icon: 'close',
    topRope: true,
    tick: false,
    topRopeTick: false,
    color: '#383838',
    order: 12,
  },
];

export const PUBLISH_OPTIONS: Registry[] = [
  { value: PublishOptionsEnum.public, label: 'Objavi povsod' },
  { value: PublishOptionsEnum.club, label: 'Samo za prijatelje' },
  { value: PublishOptionsEnum.log, label: 'Javno na mojem profilu' },
  { value: PublishOptionsEnum.private, label: 'Samo zame' },
];

export const ACTIVITY_TYPES: Registry[] = [
  { value: 'crag', label: 'Dan v plezališču', color: '#383838' },
  { value: 'climbingGym', label: 'Plezalni center', color: '#1C508C' },
  { value: 'trainingGym', label: 'Telovadnica', color: '#8C2A1E' },
  { value: 'peak', label: 'Osvojen vrh', color: '#383838' },
  { value: 'iceFall', label: 'Slap', color: '#383838' },
  { value: 'other', label: 'Ostalo', color: '#ECAAA1' },
];
